version: '3.1'
services:
  springboot:
    build:
        context: .
        dockerfile: DockerFile
    restart: always
    container_name: facturacioncontainer
    ports:
     - "8080:8080"
    working_dir: /opt/app

